package twcapbot

import (
	"fmt"
	"github.com/gusanmaz/twigger"
)

const BotName = "Tweet Captioner Bot"

var infoNoteTempl = "This tweet could be reached from following URL: %v"

var (
	botScreenName    string
	botAndScreenName string
	endNotes1        string
	endNotes2        string
	endNotes3        string
	endNotes         string
	videoNote        string
	gifNote          string
)

// This function should be called shortly after the bot is created
func SetBotScreenName(botScreenName string) {
	botScreenName = botScreenName
	botAndScreenName = fmt.Sprintf("%v (@%v)", BotName, botScreenName)
	endNotes1 = fmt.Sprintf("Generated by %v.", botAndScreenName)
	endNotes2 = "The bot is currently at it's early beta stage."
	endNotes3 = "Feedbacks are appreciated 😇"

	endNotes = fmt.Sprintf("%v %v %v", endNotes1, endNotes2, endNotes3)
	videoNote = fmt.Sprintf("%v cannot properly captionize video tweets for now.", botAndScreenName)
	gifNote = fmt.Sprintf("%v cannot propery captionize tweets with GIF images for now", botAndScreenName)
}

func GetCaptionsForTweet(tw twigger.Tweet, quotedTweet *twigger.Tweet) []string {
	captions := make([]string, 0)
	warningNote := []string{}
	textNote := ""
	infoNote := ""

	action := "tweet"
	if tw.Retweeted {
		action = "retweet"
	}

	if quotedTweet == nil {
		textNote = fmt.Sprintf("%v (@%v) %ved: %v", tw.User.Name, tw.User.ScreenName, action, tw.FullText)
		infoNote = fmt.Sprintf(infoNoteTempl, GetTweetURL(tw))

		if tw.ContainsVideo() {
			warningNote = append(warningNote, videoNote)
		}
		if tw.ContainsGIF() {
			warningNote = append(warningNote, gifNote)
		}
	} else {
		textNote = fmt.Sprintf("%v (@%v) tweeted: %v <br/><br/>", tw.User.Name, tw.User.ScreenName, tw.FullText)
		quoterScreenName := tw.User.ScreenName
		quoterName := tw.User.Name
		if tw.RetweetedStatus != nil {
			quoterScreenName = tw.RetweetedStatus.User.ScreenName
		}

		textNote += fmt.Sprintf("%v (@%v) quoted tweet of %v <br/><br/>", quoterName, quoterScreenName, quotedTweet.User.ScreenName) // (???)
		textNote += fmt.Sprintf("Original tweet's content: %v <br/><br/>", tw.FullText)
		textNote += fmt.Sprintf("Quoted tweet's content: %v", quotedTweet.FullText)

		originalTweetInfoNote := fmt.Sprintf(infoNoteTempl, GetTweetURL(tw))
		quotedTweetInfoNote := fmt.Sprintf(infoNoteTempl, GetTweetURL(*quotedTweet))
		infoNote = fmt.Sprintf("Original Tweet URL: %v <br/><br/>Quoted tweet URL: %v", originalTweetInfoNote, quotedTweetInfoNote)

		originalTweetHasSpecialMedia := tw.ContainsGIF() || tw.ContainsVideo()
		quotedTweetHasSpecialMedia := quotedTweet.ContainsGIF() || quotedTweet.ContainsVideo()

		if originalTweetHasSpecialMedia {
			if tw.ContainsVideo() {
				warningNote = append(warningNote, videoNote)
			}
			if tw.ContainsGIF() {
				warningNote = append(warningNote, gifNote)
			}
		} else if quotedTweetHasSpecialMedia {
			if quotedTweet.ContainsVideo() {
				warningNote = append(warningNote, videoNote)
			}
			if quotedTweet.ContainsGIF() {
				warningNote = append(warningNote, gifNote)
			}
		}
	}

	captions = append(captions, textNote, infoNote)
	captions = append(captions, warningNote...)
	captions = append(captions, endNotes)

	return captions
}
